// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjxZMEnTdbW9ZBXIUtlzhTqurNapTv8I',
    appId: '1:827641015183:web:002cf41166d75d07a8b9fa',
    messagingSenderId: '827641015183',
    projectId: 'test-be1b1',
    authDomain: 'test-be1b1.firebaseapp.com',
    storageBucket: 'test-be1b1.appspot.com',
    measurementId: 'G-ZB3X4JLSJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMdt9vTv9sP8KfOtfCZ87e554Xhl5uc0',
    appId: '1:827641015183:android:b1bc6ff52ae8e8faa8b9fa',
    messagingSenderId: '827641015183',
    projectId: 'test-be1b1',
    storageBucket: 'test-be1b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwEQ9JI0VNbhxYfH0QV-NqckjmQewkGt4',
    appId: '1:827641015183:ios:56f2668dbd53209da8b9fa',
    messagingSenderId: '827641015183',
    projectId: 'test-be1b1',
    storageBucket: 'test-be1b1.appspot.com',
    androidClientId: '827641015183-c70uinbnpa5qrdtqdmv4ct5mchufc226.apps.googleusercontent.com',
    iosClientId: '827641015183-uemvolkuh56ousqk58dhaq4s8c863ppn.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwEQ9JI0VNbhxYfH0QV-NqckjmQewkGt4',
    appId: '1:827641015183:ios:0d8ad036ad42c869a8b9fa',
    messagingSenderId: '827641015183',
    projectId: 'test-be1b1',
    storageBucket: 'test-be1b1.appspot.com',
    androidClientId: '827641015183-c70uinbnpa5qrdtqdmv4ct5mchufc226.apps.googleusercontent.com',
    iosClientId: '827641015183-p6gq9mudceoa9s1n7gg232na1usdhmn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.noblWebBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZjxZMEnTdbW9ZBXIUtlzhTqurNapTv8I',
    appId: '1:827641015183:web:2df0bbb2eec6fb08a8b9fa',
    messagingSenderId: '827641015183',
    projectId: 'test-be1b1',
    authDomain: 'test-be1b1.firebaseapp.com',
    storageBucket: 'test-be1b1.appspot.com',
    measurementId: 'G-H4NGCH4FBS',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCZjxZMEnTdbW9ZBXIUtlzhTqurNapTv8I',
    appId: '1:827641015183:web:328e6d4f1128990ba8b9fa',
    messagingSenderId: '827641015183',
    projectId: 'test-be1b1',
    authDomain: 'test-be1b1.firebaseapp.com',
    storageBucket: 'test-be1b1.appspot.com',
    measurementId: 'G-J59RSXVHPK',
  );
}
